#!/bin/bash

#realpath() {
    #[[ $1 = /* ]] && echo "$1" || echo "$(pwd -P)/${1#./}"
#}

#realpath $1

#!/bin/sh

# TARGET_FILE=$1

# if [[ -e "$1" ]]
# then 
#     :
# else
#     echo "$0: $1:No such file or directory" 
#     exit 1
# fi

# cd `dirname $TARGET_FILE`
# TARGET_FILE=`basename $TARGET_FILE`

# # Iterate down a (possible) chain of symlinks
# while [ -L "$TARGET_FILE" ]
# do
#     TARGET_FILE=`readlink $TARGET_FILE`
#     cd `dirname $TARGET_FILE`
#     TARGET_FILE=`basename $TARGET_FILE`
# done

# # Compute the canonicalized name by finding the physical path 
# # for the directory we're in and appending the target file.
# PHYS_DIR=`pwd -P`
# RESULT=$PHYS_DIR/$TARGET_FILE
# echo $RESULT

function __realpath__(){
    local CURRENT_DIR=$(pwd)
    local TARGET_FILE=$1
    if [[ -e "$1" ]]
    then
        :
    else
        echo "$0: $1:No such file or directory" 
        return 1
    fi

    cd `dirname $TARGET_FILE`
    TARGET_FILE=`basename $TARGET_FILE`

    # Iterate down a (possible) chain of symlinks
    while [ -L "$TARGET_FILE" ]
    do
        TARGET_FILE=`readlink $TARGET_FILE`
        cd `dirname $TARGET_FILE`
        TARGET_FILE=`basename $TARGET_FILE`
    done

    # Compute the canonicalized name by finding the physical path 
    # for the directory we're in and appending the target file.
    local PHYS_DIR=`pwd -P`
    local RESULT=$PHYS_DIR/$TARGET_FILE
    echo $RESULT
    cd ${CURRENT_DIR}
}
